name: flutter_tutorial
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  dio: ^5.3.3
  retrofit_generator: ^8.0.4
  freezed: ^2.4.5
  webview_flutter: ^4.4.2
  provider: ^6.1.1
  flutter_riverpod: ^2.4.6
  riverpod_generator: ^2.3.6
  riverpod_annotation: ^2.3.1
  flutter_hooks: ^0.20.3
  pretty_dio_logger: ^1.3.1
  pedantic_mono: ^1.24.0+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true
